version: '3'
services:
  proxy:
    container_name: "reverse_proxy"
    build: ./
    networks:
      - site1
      - site2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme-challenge:/tmp/acme-challenge

networks:
  site1:
    external:
      name: site1_default
  site2:
    external:
      name: site2_default
